version: '3.5'

services:
    app:
        image: main-wine-app:latest
        container_name: adega-main-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:8080"
        command: npm start
        networks:
            - adega-net
        tty: true

    test-service:
        image: adega-api-test:latest
        container_name: adega-api-test
        build:
            context: ./services/test-service/
            dockerfile: Dockerfile
        ports:
            - "3001:8080"
        command: npm start
        networks:
            - adega-net
        tty: true

    main-backend-service:
        image: adega-api-backend-main:latest
        container_name: adega-backend-main
        build:
            context: ./services/adega-backend/
            dockerfile: Dockerfile
        ports:
            - "3002:8080"
        command: npm start
        networks:
            - adega-net
        tty: true

networks:
    adega-net:
        name: adega-network
        external: false