version: '3.5'

services:
    app:
        image: main-adega-app:latest
        container_name: adega-wine-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        command: npm start
        networks:
            - adega-net
        tty: true

    test-service:
        image: adega-api-test:latest
        container_name: adega-api-test
        build:
            context: ./services/test-service/
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        command: npm start
        networks:
            - adega-net
        tty: true

networks:
    adega-net:
        name: adega-network
        external: false

