services:
    app:
        container_name: adega-main-container
        restart: always
        build:
            context: ./wine-store-app/
            dockerfile: Dockerfile
        volumes:
            - ./wine-store-app/public:/usr/src/app/public
            - ./wine-store-app/src:/usr/src/app/src
        environment:
            - env=${ENVIRONMENT}
        ports:
            - "${APP_PORT}:8080"
        #command: npm start
        command: npm run dev
        networks:
            - adega-net
        tty: true

    main-backend-service:
        container_name: adega-backend-main
        build:
            context: ./wine-server-service/
            dockerfile: Dockerfile
        volumes:
            - ./wine-server-service/database:/usr/src/app/database
            - ./wine-server-service/src:/usr/src/app/src
        ports:
            - "${SERVER_PORT}:8080"
        command: npm start
        networks:
            - adega-net
        tty: true

networks:
    adega-net:
        name: adega-network
        external: false