services:
    app-dev:
        container_name: adega-container-dev
        restart: always
        build:
            context: ./app
            dockerfile: Dockerfile
        environment:
            ENVIRONMENT: development
        volumes:
            - ./app/public:/usr/src/app/public
            - ./app/src:/usr/src/app/src
        ports:
            - "${APP_PORT}:8080"
        command: npm run dev
        networks:
            - adega-net
        tty: true
        profiles: [ "dev" ]

    app-release:
        container_name: adega-container-release
        restart: always
        build:
            context: ./app
            dockerfile: Dockerfile.release
        environment:
            ENVIRONMENT: release
        ports:
            - "${APP_PORT}:8080"
        command: npm run start
        networks:
            - adega-net
        tty: true
        profiles: [ "release" ]

    backend-service-dev:
        container_name: adega-backend-dev
        restart: always
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            ENVIRONMENT: development
            POSTGRES_DB_NAME: ${DATABASE_NAME}
            POSTGRES_DB_LOGIN: ${DATABASE_LOGIN}
            POSTGRES_DB_PASSWD: ${DATABASE_PASSWD}
        volumes:
            - ./backend/src:/usr/src/app/src
        ports:
            - "${SERVER_PORT}:8080"
        depends_on:
            - database
        command: npm run dev
        networks:
            - adega-net
        tty: true
        profiles: [ "dev" ]

    # JavaScript frontend code bundler
    webpack-bundler-dev:
        container_name: webpack-bundler-dev
        build:
            context: ./webpack-bundler
            dockerfile: Dockerfile
        volumes:
            - ./app/private/sourcejs:/app/sourcejs
            - ./app/public/src:/app/outdir
        working_dir: /app
        command: npm run dev
        profiles: [ "dev" ]

    webpack-bundler-release:
        container_name: webpack-bundler-release
        build:
            context: ./webpack-bundler
            dockerfile: Dockerfile
        volumes:
            - ./app/private/sourcejs:/app/sourcejs
            - ./app/public/src:/app/outdir
        working_dir: /app
        command: npm run build
        profiles: [ "release" ]

    database:
        container_name: postgres-db-container-dev
        build:
            context: ./postgres-db
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: ${DATABASE_LOGIN}
            POSTGRES_PASSWORD: ${DATABASE_PASSWD}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - "${DATABASE_PORT}:5432"
        networks:
            - adega-net
        tty: true
        profiles: [ "dev", "release" ]

networks:
    adega-net:
        name: adega-network
        external: false